<?php
/**
 * Copyright (c) 2013 Man4x
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *
 * @project     Magento Man4x Mondial Relay Module
 * @desc        Template for dealing Mondial Relay shipping methods with Paypal Express Checkout
 * (pick-up selection and pick-up info)
 *              Added through handle <checkout_onepage_shippingmethod>
 * @block       Man4x_MondialRelay_Block_Info
 * @author      Emmanuel Catrysse (man4x[@]hotmail[.]fr)
 * @license     http://www.opensource.org/licenses/MIT  The MIT License (MIT)
 */
?>

<script type="text/javascript">
//<![CDATA[
    $('shipping_method').options.each(
        function(e, i) {
            if (e.value == 'mondialrelaypickup_24R') {
                e.text = "<?php echo (Mage::helper('mondialrelay')->__('Click to select your pick-up location')); ?>";
                throw $break;
            }
        }
    );
    
    function anchorToSelectedPickup(e) {
        // return element where to insert selected pickup div
        return $(e.parentNode);
    }
    
    Event.observe($('shipping_method'), 'change', function()
    {
        if (this.getValue() == 'mondialrelaypickup_24R') {
            if ($('pickup-selected')) {$('pickup-selected').show();
            if ($('pickup_popup')) {$('pickup_popup').show();}
            else {
                $(document.body).insert({bottom: '<div id="pickup_popup"></div>'});
                new Ajax.Request('<?php echo $this->getPickupPopupUrl(); ?>', {
                    evalScripts:    true,
                    onCreate:       function() {$('pickup-please-wait').show();},
                    onSuccess:      function(transport) {
                                        $('pickup-please-wait').hide();
                                        $('pickup_popup').update();
                                        $('pickup_popup').update(transport.responseText);
                                    }
                    }
                 );
                _parent = anchorToSelectedPickup();
                var _divWait = new Element('div', {id: 'pickup-please-wait', style: 'display:none;'}).update("<img src='<?php echo $this->getSkinUrl('images/Man4x_MondialRelay/mondialrelay_ajax_loading_50x55.gif')?>' />");
                _parent.insert(_divWait);
                var _div = new Element('div', {id: 'pickup-selected', style: 'display:none;'}).update("<p class='message'><?php echo (Mage::helper('mondialrelay')->__('Selected pick-up:'))?></p><div id='pickup-address'></p>");
                _parent.insert(_div);
            }
        }
    });
//]]>
</script>